// LIFE SKILL ONTOLOGY v2: broad domains are bundled; individual progress stays in the player's save data.
const domains = [
  ["human-basics","HUMAN BASICS",["Walking","Running","Balance","Fine Motor Control","Hand-Eye Coordination","Reading","Listening","Speech","Memory Recall","Attention Control","Self Care","Mobile Device Operation"]],
  ["language","LANGUAGE & COMMUNICATION",["Japanese","Written Japanese","Conversation","Public Speaking","Active Listening","Foreign Language Learning","Translation","Writing","Storytelling","Negotiation","Presentation","Nonverbal Communication"]],
  ["cognition","COGNITION",["Logical Reasoning","Problem Solving","Information Research","Critical Thinking","Systems Thinking","Pattern Recognition","Observation","Decision Making","Learning Strategy","Mental Modelling","Planning","Time Estimation"]],
  ["digital","DIGITAL",["Typing","Touch Typing","File Management","Web Literacy","Data Literacy","Programming","Debugging","Automation","AI Tools","Digital Security","UX Literacy","Online Research"]],
  ["creative","CREATIVE",["Visual Design","Photography","Illustration","Music Listening","Music Performance","Video Editing","Creative Writing","Idea Generation","Colour Theory","Composition","Art Direction","Creative Critique"]],
  ["daily-life","DAILY LIFE",["Cooking","Food Safety","Meal Planning","Cleaning","Laundry","Money Handling","Shopping","Home Organisation","Sleep Routine","Personal Care","Wardrobe Management","Emergency Preparation"]],
  ["physical","PHYSICAL",["Strength Training","Endurance","Flexibility","Posture","Breathing","Recovery","Rhythm","Dance","Swimming","Cycling","Sport Strategy","Body Awareness"]],
  ["world","WORLD & NAVIGATION",["Map Reading","Route Planning","Urban Navigation","Public Transit","Exploration","Weather Awareness","Travel Planning","Place Memory","Risk Awareness","Outdoor Safety","Local Discovery","Wayfinding"]],
  ["social","SOCIAL",["Empathy","Perspective Taking","Conflict Resolution","Collaboration","Boundary Setting","Relationship Maintenance","Facilitation","Mentoring","Community Participation","Hospitality","Interviewing","Feedback"]],
  ["business","BUSINESS & WORK",["Project Management","Requirements Analysis","Documentation","Meeting Design","Task Prioritisation","Customer Understanding","Budgeting","Sales Conversation","Operations","Leadership","Career Planning","Professional Ethics"]],
  ["science","SCIENCE & KNOWLEDGE",["Scientific Method","Mathematics","Statistics","Experiment Design","Data Interpretation","Biology","Chemistry","Physics","Psychology","History","Geography","Economics"]],
  ["engineering","ENGINEERING & MAKING",["Tool Handling","Prototyping","Mechanical Reasoning","Electronics","Repair","3D Modelling","Architecture Literacy","Construction Safety","Material Knowledge","Quality Control","Technical Drawing","Process Design"]],
  ["nature","NATURE & LIFE",["Plant Recognition","Animal Recognition","Ecology","Seasonal Awareness","Gardening","Foraging Safety","Stargazing","Geology","Weather Reading","Nature Photography","Conservation","Field Observation"]],
  ["culture","CULTURE & SOCIETY",["Film Literacy","Literature","Museum Literacy","Food Culture","Fashion Literacy","Religion Literacy","Cultural History","Media Literacy","Civic Literacy","Etiquette","Festival Knowledge","Travel Culture"]],
  ["craft","CRAFT & MATERIAL",["Sewing","Knitting","Woodworking","Ceramics","Paper Craft","Calligraphy","Baking","Flower Arrangement","Makeup","Nail Care","Leatherwork","Instrument Care"]],
  ["health","HEALTH & CARE",["Health Literacy","Nutrition","Hydration","First Aid Awareness","Medication Management","Mental Health Literacy","Stress Regulation","Ergonomics","Dental Care","Injury Prevention","Health Communication","Care Planning"]],
  ["education","LEARNING & EDUCATION",["Note Taking","Study Planning","Memory Techniques","Exam Strategy","Teaching","Tutoring","Curriculum Design","Academic Writing","Citation Practice","Language Study","Self Assessment","Practice Design"]],
  ["mathematics","MATHEMATICS",["Arithmetic","Algebra","Geometry","Calculus","Probability","Discrete Mathematics","Financial Mathematics","Mathematical Proof","Modelling","Estimation","Spreadsheet Maths","Quantitative Reasoning"]],
  ["computing","COMPUTING",["Algorithms","Databases","Networks","Web Development","Mobile Development","Version Control","Cloud Computing","Testing","API Design","Data Visualisation","Machine Learning","Accessibility Engineering"]],
  ["design","DESIGN & PRODUCT",["User Research","Interaction Design","Interface Design","Design Systems","Information Architecture","Prototyping","Service Design","Product Strategy","Usability Testing","Design Writing","Motion Design","Brand Design"]],
  ["media","MEDIA & BROADCAST",["Journalism","Interview Production","Audio Editing","Podcasting","Scriptwriting","Cinematography","Lighting","Sound Design","Live Streaming","Publishing","Audience Analysis","Media Ethics"]],
  ["music","MUSIC",["Rhythm Reading","Music Theory","Ear Training","Singing","Keyboard","Guitar","Ensemble Playing","Arrangement","Recording","Mixing","Music Production","Performance Presence"]],
  ["performing","PERFORMING ARTS",["Acting","Improvisation","Stage Movement","Voice Projection","Choreography","Stagecraft","Directing","Rehearsal Process","Audience Awareness","Comedy","Story Performance","Event Performance"]],
  ["writing","WRITING & LANGUAGE ARTS",["Journaling","Essay Writing","Copywriting","Editing","Proofreading","Poetry","Screenwriting","Research Writing","Long-form Writing","Worldbuilding","Rhetoric","Publishing Workflow"]],
  ["visual-arts","VISUAL ARTS",["Drawing","Painting","Printmaking","Sculpture","Digital Illustration","Figure Study","Perspective","Visual Storytelling","Art History","Gallery Practice","Portfolio Curation","Creative Process"]],
  ["food","FOOD & HOSPITALITY",["Ingredient Knowledge","Knife Skills","Heat Control","Baking Science","Fermentation","Menu Planning","Food Presentation","Coffee Brewing","Tea Preparation","Hosting","Restaurant Literacy","Kitchen Workflow"]],
  ["fashion","FASHION & PERSONAL STYLE",["Fit Assessment","Colour Coordination","Fabric Knowledge","Styling","Garment Care","Wardrobe Editing","Shopping Strategy","Personal Branding","Hair Styling","Skincare","Accessory Design","Sustainable Fashion"]],
  ["home","HOME & LIVING",["Space Planning","Interior Styling","Home Maintenance","Household Budget","Utility Management","Decluttering","Guest Preparation","Safety Inspection","Plant Care","Seasonal Living","Moving Logistics","Repair Scheduling"]],
  ["finance","FINANCE",["Personal Budgeting","Saving","Banking","Taxes","Insurance Literacy","Investing Literacy","Credit Management","Consumer Rights","Price Comparison","Financial Planning","Bookkeeping","Economic Decisions"]],
  ["law","LAW & CIVIC LIFE",["Legal Literacy","Contract Reading","Privacy Awareness","Digital Rights","Workplace Rights","Civic Participation","Public Services","Dispute Resolution","Policy Reading","Ethical Reasoning","Documentation Practice","Emergency Procedures"]],
  ["language-world","WORLD LANGUAGES",["English Listening","English Speaking","English Reading","English Writing","Chinese Basics","Korean Basics","French Basics","Spanish Basics","Pronunciation","Intercultural Communication","Language Exchange","Translation Tools"]],
  ["travel","TRAVEL & FIELD",["Trip Research","Packing","Booking","Airport Navigation","Accommodation Skills","Local Etiquette","Travel Budgeting","Travel Safety","Itinerary Design","Solo Travel","Group Travel","Travel Documentation"]],
  ["outdoors","OUTDOOR & ADVENTURE",["Hiking","Camping","Trail Navigation","Cycling Routes","Water Safety","Sun Protection","Layering","Wildlife Safety","Leave No Trace","Emergency Signalling","Distance Pacing","Outdoor Cooking"]],
  ["sports","SPORTS & PLAY",["Game Rules","Team Play","Training Plan","Warm Up","Competitive Mindset","Refereeing","Racket Sports","Ball Sports","Running Form","Swimming Technique","Martial Arts Basics","Play Strategy"]],
  ["caregiving","CARE & SUPPORT",["Childcare","Elder Support","Active Care Listening","Accessibility Awareness","Inclusive Communication","Meal Support","Appointment Support","Care Documentation","Crisis Support","Community Care","Peer Support","Advocacy"]],
  ["research","RESEARCH & ANALYSIS",["Question Framing","Literature Search","Source Evaluation","Survey Design","Interview Research","Qualitative Analysis","Quantitative Analysis","Data Cleaning","Evidence Synthesis","Research Ethics","Report Writing","Peer Review"]],
  ["management","ORGANISATION & LEADERSHIP",["Goal Setting","Delegation","Team Coordination","Risk Management","Change Management","Decision Facilitation","Resource Planning","Stakeholder Mapping","Process Improvement","Conflict Mediation","Performance Review","Strategic Thinking"]],
  ["entrepreneurship","ENTREPRENEURSHIP",["Opportunity Discovery","Business Modelling","Market Research","Pricing","Pitching","Customer Discovery","Brand Strategy","Launch Planning","Partnerships","Growth Strategy","Business Operations","Founder Resilience"]],
  ["languages-code","CODE & LOGIC",["JavaScript","Python","HTML","CSS","SQL","Shell Basics","Git Workflow","Code Review","Refactoring","Security Basics","Performance Tuning","Technical Documentation"]],
  ["maker","DIGITAL FABRICATION",["3D Printing","Laser Cutting","CAD","Microcontrollers","Sensors","Robotics","Wearable Tech","Physical Computing","Soldering","Circuit Design","Prototype Testing","Fabrication Safety"]],
  ["architecture","ARCHITECTURE & BUILT WORLD",["Spatial Drawing","Building Materials","Building Codes Literacy","Site Analysis","Floor Planning","Landscape Design","Urban Design","Structural Awareness","Lighting Planning","Furniture Layout","Model Making","Universal Design"]],
  ["agriculture","AGRICULTURE & FOOD SYSTEMS",["Soil Care","Seed Starting","Crop Planning","Composting","Irrigation","Pest Management","Harvesting","Food Preservation","Farm Safety","Seasonal Crops","Urban Farming","Supply Chains"]],
  ["clinical","CLINICAL & WELLNESS SUPPORT",["Vital Signs Awareness","Patient Communication","Anatomy Literacy","Hygiene Practice","Care Ethics","Health Records","Rehabilitation Basics","Nutrition Support","Sleep Science","Public Health Literacy","Safety Triage","Clinical Research Literacy"]],
  ["emergency","SAFETY & EMERGENCY",["Emergency Calling","Evacuation","Fire Safety","Earthquake Readiness","Flood Readiness","CPR Awareness","Incident Reporting","Personal Safety","Digital Emergency Plan","Disaster Kit","Crisis Communication","Community Response"]],
  ["environment","ENVIRONMENT & CLIMATE",["Climate Literacy","Carbon Awareness","Waste Sorting","Circular Economy","Energy Saving","Water Stewardship","Biodiversity Support","Environmental Policy","Sustainable Purchasing","Climate Communication","Air Quality Awareness","Environmental Data"]],
  ["linguistics","LINGUISTICS",["Phonetics","Grammar Analysis","Semantics","Pragmatics","Language History","Language Documentation","Dialect Awareness","Corpus Literacy","Language Acquisition","Discourse Analysis","Writing Systems","Lexicography"]],
  ["philosophy","PHILOSOPHY & IDEAS",["Logic History","Ethics","Epistemology","Argument Analysis","Political Philosophy","Aesthetics","Philosophy of Mind","Science Philosophy","Comparative Thought","Moral Deliberation","Concept Mapping","Reflective Practice"]],
  ["religion","RELIGION & BELIEF",["Religious Literacy","Ritual Awareness","Comparative Religion","Sacred Text Literacy","Belief Dialogue","Pilgrimage Culture","Festival Practice","Ethical Traditions","Spiritual Reflection","Interfaith Communication","Cultural Sensitivity","Community Traditions"]],
  ["marketing","MARKETING & GROWTH",["Audience Research","Positioning","Messaging","Content Strategy","SEO Literacy","Social Media Strategy","Campaign Planning","Email Communication","Analytics","Community Growth","Conversion Design","Brand Measurement"]],
  ["people","PEOPLE & HUMAN RESOURCES",["Hiring Literacy","Onboarding","Career Coaching","Workplace Culture","Compensation Literacy","People Analytics","Team Wellbeing","Inclusive Hiring","Training Programmes","Performance Support","Workplace Mediation","Organisation Design"]],
  ["logistics","LOGISTICS & OPERATIONS",["Inventory Control","Procurement","Scheduling","Warehouse Literacy","Route Optimisation","Vendor Coordination","Demand Forecasting","Quality Assurance","Process Mapping","Operations Metrics","Last Mile Delivery","Supply Risk"]],
  ["manufacturing","MANUFACTURING",["Assembly","Lean Basics","Machine Safety","Production Planning","Quality Inspection","Maintenance Planning","Materials Handling","Factory Workflow","Tool Calibration","Process Documentation","Industrial Design","Manufacturing Systems"]],
  ["security","SECURITY & RESILIENCE",["Password Hygiene","Threat Awareness","Privacy Settings","Incident Response","Secure Communication","Physical Security","Fraud Awareness","Data Backup","Risk Assessment","Security Policy","Identity Protection","Resilience Planning"]],
  ["gaming","GAMES & INTERACTIVE WORLD",["Game Literacy","Level Design","Game Writing","Mechanics Design","Playtesting","Community Play","Esports Awareness","Game Accessibility","Interactive Narrative","Game Production","Systems Balancing","Digital Citizenship"]],
  ["animation","ANIMATION & MOTION",["Storyboarding","2D Animation","3D Animation","Character Design","Motion Graphics","Editing Rhythm","Visual Effects","Rigging Literacy","Scene Layout","Animation Timing","Portfolio Reel","Production Pipeline"]],
  ["beauty","BEAUTY & GROOMING",["Skin Analysis","Makeup Technique","Haircare","Hair Colour Literacy","Fragrance","Nail Art","Personal Grooming","Salon Communication","Cosmetic Safety","Colour Matching","Beauty Product Literacy","Self Expression"]],
  ["automotive","AUTOMOTIVE & MOBILITY",["Road Safety","Vehicle Care","Driving Theory","Navigation Systems","Bicycle Maintenance","Public Mobility","Electric Vehicle Literacy","Traffic Rules","Trip Inspection","Ride Planning","Mobility Accessibility","Transport Technology"]],
  ["aviation","AVIATION & SPACE",["Flight Planning","Airport Systems","Weather for Flight","Air Navigation","Aircraft Literacy","Space Science","Satellite Literacy","Drone Safety","Aerospace History","Flight Communication","Travel Documentation","Observation Astronomy"]],
  ["marine","MARINE & WATER WORLD",["Water Navigation","Tide Awareness","Boat Safety","Marine Ecology","Fishing Literacy","Coastal Weather","Water Sports Safety","Harbour Systems","Ocean Conservation","Seamanship","Marine Geography","Aquatic Observation"]],
  ["public-service","PUBLIC SERVICE & SOCIETY",["Government Literacy","Community Planning","Public Speaking","Social Policy","Volunteer Coordination","Public Consultation","Civic Data","Accessibility Services","Nonprofit Operations","Community Events","Public Communication","Social Innovation"]]
];

const composite = [
  ["structured-writing","Structured Writing",["language","cognition"]], ["technical-writing","Technical Writing",["structured-writing","business","digital"]], ["information-communication","Information Communication",["technical-writing","creative","social"]], ["world-routing","World Routing",["world","cognition","daily-life"]], ["meal-preparation","Meal Preparation",["daily-life","cognition"]], ["creative-technology","Creative Technology",["creative","digital"]], ["research-synthesis","Research Synthesis",["cognition","science","language"]], ["digital-production","Digital Production",["digital","business","creative"]], ["life-design","Life Design",["daily-life","cognition","world"]], ["human-centred-design","Human-centred Design",["design","research","social"]], ["creative-direction","Creative Direction",["visual-arts","design","media"]], ["independent-learning","Independent Learning",["education","cognition","research"]], ["personal-finance","Personal Finance",["finance","mathematics","law"]], ["world-traveller","World Traveller",["travel","language-world","world"]], ["digital-maker","Digital Maker",["computing","maker","engineering"]], ["healthy-living","Healthy Living",["health","food","physical"]], ["community-builder","Community Builder",["social","caregiving","management"]], ["performer","Live Performer",["music","performing","media"]]
];

export const skillNodes = domains.flatMap(([id,label,skills], domainIndex) => {
  const angle = -Math.PI / 2 + domainIndex * (Math.PI * 2 / domains.length); const x = 500 + Math.cos(angle) * 270; const y = 360 + Math.sin(angle) * 220;
  const root = { id, label, domain:label, kind:"cluster", requires:[], x, y };
  return [root, ...skills.map((skill,index) => { const branchAngle = angle + (index - (skills.length - 1) / 2) * .105; return { id:`${id}-${index}`, label:skill, domain:label, kind:"skill", requires:[id], x:500 + Math.cos(branchAngle) * (345 + (index % 3) * 24), y:360 + Math.sin(branchAngle) * (285 + (index % 3) * 20) }; })];
}).concat(composite.map(([id,label,requires], index) => ({ id,label,domain:"COMPOSITE",kind:"composite",requires,x:410 + (index % 3) * 92,y:285 + Math.floor(index / 3) * 78 })));

export const skillDomains = domains.map(([id,label]) => ({ id,label }));
